### ISSUE TITLE
"Contribute to the translation" button creates a file in the wrong folder 

### ISSUE THREAD

**Issue by Resxt** [plutoniummod/landing#121]
Whenever you look at a page in a non english language ([for example this one](https://plutonium.pw/fr/docs/server/iw5/setting-up-a-server/)) and click on "contribute to the translation" on the blue ribbon at the top of the screen it makes you create a new file in `src/pages` instead of the correct folder which is `src/pages/docs`.

Example here: https://github.com/plutoniummod/landing/new/develop/src/pages/docs?filename=index.fr.mdx

Two potential fixes I found are:

- Removing the parameter in the link like this `https://github.com/plutoniummod/landing/new/develop/src/pages/docs/index.fr.mdx` but it's not ideal as it makes it look like you have to enter a file name
- Adding a slash and a random character like `/a` after the docs part `https://github.com/plutoniummod/landing/new/develop/src/pages/docs/a?filename=index.fr.mdx`. It makes it work as expected but having a random letter in the url is unexpected and not ideal

**Comment by discreetbinger** [comment]
I clicked on 'contributing a translation' on the example link and it creates a file on src/pages/docs/server, which is neither of the two folders you mentioned.

**Comment by chxseh** [comment]
> I clicked on 'contributing a translation' on the example link and it creates a file on src/pages/docs/server, which is neither of the two folders you mentioned.

Clicking the contribute a translation button on a regional page still puts it in the wrong place.

When the example link is clicked, you are sent here:
![img](https://i.chse.dev/aXWFSl)
However, this is incorrect. 
The correct place should be this
![img](https://i.chse.dev/fdcKRz)

**Comment by discreetbinger** [comment]
Thanks for clarifying, I might have a go at this.

**Comment by discreetbinger** [comment]
I believe I have now fixed this by following https://github.com/isaacs/github/issues/1527#issuecomment-617466083.
