### ISSUE TITLE
Kick bug when playes have same IP

### ISSUE THREAD

**Issue by 1Adri1** [plutoniummod/landing#140]
When I play with my friends in the same network (lan party) all players get kicked from the server when one player leaves to change his class or graphics settings.

We experienced that with BO2 multiplayer.
After that we stopped playing plutonium, because that was verry annoying.

I hope you can / will fix that 😉

**Comment by 1Adri1** [comment]
I postet that in the forum.

**Comment by Resxt** [comment]
@1Adri1 This is the website/documentation's Github repository, it's not a place to discuss game bugs, stick to the forum
